Add templates for S3 invoicing
vshn/appuio-odoo-adapter pull request #54
Opened 2022-07-27 09:45 UTC by davidgubler

## Summary

* Add templates for S3 invoicing

2022-07-27 10:48 UTC, Kidswiss commented
Could you maybe provide a PDF/Screenshot of a generated invoice? So that I can see what these templates actually do.

2022-07-27 12:17 UTC, davidgubler commented
[account.report_invoice.pdf](https://github.com/vshn/appuio-odoo-adapter/files/9198597/account.report_invoice.pdf)

Here's a test invoice I've generated with these templates.

2022-07-28 07:01 UTC, tobru requested changes
The description needs to be changed, please use "Object Storage" instead of "S3" as the product is called like that (S3 is the name of the AWS product for Object Storage).

2022-07-28 07:01 UTC, tobru commented on description_templates/s3-storage:c-appuio-cloudscale-lpg-2.gotmpl
> +S3 Storage Cloudscale
Object Storage - Storage (cloudscale.ch)

2022-07-28 07:01 UTC, tobru commented on description_templates/s3-traffic-out:c-appuio-cloudscale-lpg-2.gotmpl
> +S3 Traffic Out Cloudscale
Object Storage - Traffic Out (cloudscale.ch)

2022-07-28 07:06 UTC, davidgubler commented
Thanks @tobru , good point about "object storage". I'll have to change this everywhere.

2022-07-28 07:36 UTC, davidgubler commented on description_templates/s3-requests:c-appuio-cloudscale-lpg-2.gotmpl
> +S3 Requests Cloudscale
Fixed.

2022-07-28 07:36 UTC, davidgubler commented on description_templates/s3-storage:c-appuio-cloudscale-lpg-2.gotmpl
> +S3 Storage Cloudscale
Fixed

2022-07-28 07:36 UTC, davidgubler commented on description_templates/s3-traffic-out:c-appuio-cloudscale-lpg-2.gotmpl
> +S3 Traffic Out Cloudscale
Fixed

2022-07-28 07:37 UTC, davidgubler commented
I've renamed everything from "S3" to "Object Storage".

New generated invoice PDF:

[account.report_invoice.pdf](https://github.com/vshn/appuio-odoo-adapter/files/9206679/account.report_invoice.pdf)

2022-07-28 07:59 UTC, tobru approved these changes
Example invoice LGTM

2022-07-28 14:43 UTC, merged